version: "3"
services:
  neo4j:
    # Adding for M1 mac users (and maybe others)
    # Neo4j does not work by default on these architectures
    platform: linux/x86_64
    image: neo4j:4.2.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      # From https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
      # From https://neo4j.com/developer/docker-run-neo4j/
      # By default, Neo4j requires authentication and requires us to first login with neo4j/neo4j
      # and set a new password. We will skip this password reset by initializing the password
      # when we create the Docker container using the --env NEO4J_AUTH=neo4j/<password> option.
      - NEO4J_AUTH=neo4j/test
      # From https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
